version: '3.7'

services:

  speedster:
    build: .
    image: flaviostutz/speedster
    environment:
      - LOG_LEVEL=debug
      - BASE_DIR=/opt/
      - MONGO_HOST=mongo
      - MONGO_USERNAME=root
      - MONGO_PASSWORD=root
    ports:
      - 50000:50000
    # volumes:
    #   - //Users/flaviostutz/Documents/development/flaviostutz/speedster/assets:/opt

  mongo:
    image: mongo:4.1.10
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root
    ports:
      - 27017-27019:27017-27019

  mongo-express:
    image: mongo-express:0.49.0
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: root
